---
# tasks file for docker
    - name: updating the system
      command: sudo apt update -y
      
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt packages
      apt:
        update_cache: "yes"
        force_apt_get: "yes"

    - name: install docker
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      notify:
        - start docker

    - name: Create docker group
      group:
       name: "docker"
       state: present

    - name: adding existing user testadmin to group docker
      user:
       name: "{{ ansible_user_id }}"
       groups: docker
       append: yes
